<pre class='metadata'>
Title:  Worklets Level 1
Status: NOTE
Group: houdini
ED: https://html.spec.whatwg.org/multipage/worklets.html
TR: https://html.spec.whatwg.org/multipage/worklets.html
Previous Version: https://www.w3.org/TR/2020/WD-worklets-1-20200908/
Shortname: worklets
Level: 1
Abstract:  The worklets API has moved to the HTML Standard
Editor: Ian Kilpatrick, ikilpatrick@chromium.org, w3cid 73001
</pre>

<link rel="canonical" href="https://html.spec.whatwg.org/multipage/worklets.html">
<meta http-equiv="refresh" content="0; URL=https://html.spec.whatwg.org/multipage/worklets.html">
